#!/usr/bin/env bash



if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER sail
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi


chmod -R ugo+rw /.composer

usermod -a -G apache sail

# chgrp apache storage bootstrap/cache 
# find /var/www/html/storage  -type f ! -name .gitignore -exec chgrp apache {} \; 
# find /var/www/html/storage -type d  -exec chgrp apache {} \; 
# find /var/www/html/bootstrap/cache  -type f ! -name .gitignore -exec chgrp apache {} \; 
# find /var/www/html/bootstrap/cache -type d  -exec chgrp apache {} \; 

# #chmod ug+rwx storage bootstrap/cache 
# find /var/www/html/storage  -type f ! -name .gitignore -exec chmod ug+rwx {} \; 
# find /var/www/html/storage -type d  -exec chmod ug+rwx {} \; 
# find /var/www/html/bootstrap/cache  -type f ! -name .gitignore -exec chmod ug+rwx {} \; 
# find /var/www/html/bootstrap/cache -type d  -exec chmod ug+rwx {} \; 

chgrp apache /var/www/html/storage/logs/laravel.log
chmod ug+rwx /var/www/html/storage/logs/laravel.log

if [ $# -gt 0 ]; then
    exec gosu $WWWUSER "$@"
else
    /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
fi
