etalkapp:
  build: ./etalkapp
  ports :
   - "88:80"
  volumes:
   - ./etalkapp/etalk-master/:/var/www/html
  links:
   - database
phpmyadmin:
   image: corbinu/docker-phpmyadmin
   ports :
    - "8080:80"
   environment:
    - MYSQL_USERNAME=root
    - MYSQL_PASSWORD=1234
   links:
    - database:mysql
database:
  build: ./db
  ports:
   - "3306:3306"
  volumes:
   - ./etalk-db/:/var/lib/mysql
  environment:
     - MYSQL_ROOT_PASSWORD=1234
     - MYSQL_DATABASE=mysite
     - MYSQL_USER=mysite
     - MYSQL_PASSWORD=1234